apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      deployment: green
  template:
    metadata:
      labels:
        app: webapp
        deployment: green
    spec:
      containers:
      - name: webapp
        image: gcr.io/[PROJECT_ID]/webapp:v2
        ports:
        - containerPort: 8080
        env:
        - name: DEPLOYMENT
          value: "Green"  # Shows 🟩
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
