apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
    deployment: blue  # Initially points to blue deployment
  ports:
    - port: 80
      targetPort: 8080
