apiVersion: v1
kind: Service
metadata:
  name: webapp-test-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
    deployment: green  # Points to green deployment for testing
  ports:
    - port: 80
      targetPort: 8080