apiVersion: v1
kind: Service
metadata:
  name: whereami
  namespace: demo
spec:
  selector:
    app: whereami
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: whereami
  namespace: demo
---
apiVersion: v1
kind: Service
metadata:
  name: whereami-west-1
  namespace: demo
spec:
  selector:
    app: whereami
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: whereami-west-1
  namespace: demo
