networks:
  app-network:
    name: app-network
services:
  # Backend API service (animator)
  animator:
    build:
      context: ./animator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - VERTEX_AI_LOCATION=${VERTEX_AI_LOCATION:-us-central1}
      # Use the container path for service account key
      - GOOGLE_APPLICATION_CREDENTIALS=/app/animator-sa-key.json
    volumes:
      # Mount the service account key
      - ./animator-sa-key.json:/app/animator-sa-key.json:ro
    networks:
      - app-network
  # Agent service (LangGraph-based)
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - BLENDER_SERVICE_URL=http://animator:8080
      - VERTEX_AI_LOCATION=${VERTEX_AI_LOCATION:-us-central1}
      # Use the container path for service account key
      - GOOGLE_APPLICATION_CREDENTIALS=/app/animator-sa-key.json
    volumes:
      # Mount the service account key
      - ./animator-sa-key.json:/app/animator-sa-key.json:ro
    depends_on:
      - animator
    networks:
      - app-network
  # Frontend web app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Set the build-time argument for the Next.js build process
        - NEXT_PUBLIC_BUILD_ENV=development
    ports:
      - "3000:8080" # Map container port 8080 to host port 3000
    environment:
      - PORT=8080
      - LANGGRAPH_ENDPOINT=http://agent:8080
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=/api
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      # Use the container path for service account key
      - GOOGLE_APPLICATION_CREDENTIALS=/app/animator-sa-key.json
    volumes:
      # Mount the service account key
      - ./animator-sa-key.json:/app/animator-sa-key.json:ro
    depends_on:
      - agent
    networks:
      - app-network
