steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${REGION}-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}/canary-demo:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${REGION}-docker.pkg.dev/$PROJECT_ID/${REPO_NAME}/canary-demo:latest'
    ]
